f=open('PythonPrograms/filehandling/demo.txt','a')
# f.write('welcome to all')
# f.write('hope you all are fine')
# print(f.read())
# a=f.read(5)
# f.seek(0)
# b=f.read()
# print(f.tell())
# print(a)
# print('_'*20)
# print(b)
# a=f.readline(5)
# b=f.readline()
# c=f.readlines()
# # print(a)
# # print(b)
# print(c)

# d=f.readlines()
# f.seek(0)
# for i in range(len(d)):
#     a=f.readline().strip()
#     # print(a)
#     print(a[::-1])

f.write('bad time\n')
f.write('aaaaaaaaaaaaaaa')